declare function Zeph(name?: string): any;
declare function Html(content: string, options: any): any;
declare function Css(content: string, options: any): any;
declare function Attribute(target: any, name?: string): any;
declare function Property(target: any, name?: string): any;
declare function onCreate(target: any, name: string): any;
declare function onEvent(target: any, eventType: string, selector?: string): any;
export { Zeph, Zeph as ZEPH, Zeph as zeph };
export { Html, Html as HTML, Html as html };
export { Css, Css as CSS, Css as css };
export { Attribute, Attribute as ATTRIBUTE, Attribute as attribute, Attribute as Attr, Attribute as ATTR, Attribute as attr };
export { Property, Property as PROPERTY, Property as property, Property as Prop, Property as PROP, Property as prop };
export { onCreate, onCreate as ONCREATE, onCreate as oncreate };
export { onEvent, onEvent as ONEVENT, onEvent as onevent };
